### ISSUE TITLE
[FEAT] 약속신청 두번째 뷰 디테일 기능 구현

### ISSUE THREAD

**Issue by yujinnee** [TeamSeeMeet/SeeMeet-iOS#31]
## 📌  Feature Issue

두번째 뷰 세부적 기능을 구현하도록 하겠습니다.
## 📝  To-do

- [x] bottomSheetView 연결하기
- [x] 상단 selectedTimeView디폴트 값 적용하기 (Local의 현재시간 ~ 한시간 뒤로 설정)
- [x] 플러스 버튼 누르면 selectedTimeView의 시간들 sheet 뷰에 추가 기능 구현하기
- [x] 오늘 날짜 빨간 셀로 만들기
- [x] 선택된 날짜 검정 셀로 만들기
- [x] 오늘을 선택하면 검정스트로크인 빨간 셀로 만들기
- [x] 오늘 이전날짜 셀은 회색 처리
- [x] 오늘이 포함된 주면 지난 주로 가는 버튼 없애기
- [x] 하루종일 스위치 키면 시작시간 종료시간 00:00 ~ 23:59로 만들기
- [x] 하루종일 스위치 켜있는 상태에서 시간 바꾸면 하루종일 스위치 끄기
- [x] 플러스 버튼 클릭시 selectedTimeView 에 있는 날짜와 시간을 하단 bottomSheetView에 추가시키기( 스택뷰에 추가 및 개수 업데이트)
- [x] 저번주, 다음주 버튼 누르면 달과 날짜들 바뀌기
- [x] 저번주, 다음주 버튼 눌렀을 때 말일과 1일이 동시에 있으면 월을 두개 띄우기
- [x] 저번주, 다음주 버튼 눌렀을 때 12월 31일과 1월 1일이 동시에 있으면 년 월 두개 띄우기
- [x] 하단 SheetView removeButton 누르면 날짜 지우고 스택뷰와 개수 업데이트하기
