### ISSUE TITLE
[FEAT] 약속 신청 두번째 뷰 week 캘린더 서버 연결

### ISSUE THREAD

**Issue by yujinnee** [TeamSeeMeet/SeeMeet-iOS#50]
## 📌  Feature Issue

약속신청 두번째 뷰 
## 📝  To-do

- [x] 두번째 뷰 get 서버 연결
- [x] 서버데이터 확인하여 일정있는지 없는지 여부 빨간 불로띄우기
- [x] 기본적으로 오늘날짜 스케줄 띄우기 
- [x] 다른날짜 선택했을 떄 그 날짜 스케줄 띄우기
- [x] 없으면 없는 라벨 띄우기
