### ISSUE TITLE
[FEAT] 약속 신청 뷰 세부 수정사항 기능 구현

### ISSUE THREAD

**Issue by yujinnee** [TeamSeeMeet/SeeMeet-iOS#75]
## 📌  Feature Issue

약속신청 뷰에서 수정해야할 몇 가지를 기능을 수정하도록 하겠습니다.

## 📝  To-do

- [x] 약속 신청 뷰에서 내용 작성 후 빈 화면 터치해서 키보드 내려가도록 하기
- [x] 약속신청 첫번째 화면 x버튼 이미지 바꾸고  두번째화면 x버튼 빼버리기
- [x] 약속신청 내용 작성 되어야 다음 버튼 활성화
- [x] bottom sheet view 에 날짜가 선택한게 1개이상 되어야 약속신청 버튼 활성화
